sudo: required
services: 
  - docker # travis CI, we need docker!

before_install:
  # - docker build -f Dockerfile.dev . # when we run this we get the ID
  # since we can't copy paste the ID, we tag it and use that tag
  - docker build -t a428tm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true a428tm/docker-react npm run test -- --coverage

deploy:
  # we will tell travis CI how to deploy to AWS
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  # DockerReact-env - you can get this from elastic beanstalk environments (this is what we created)
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-992750928853"
  # bucket_path is going to equal the app name (see "app" above)
  bucket_path: "docker-react"
  # language: generic
  on: # this is saying... only code is pushed to master, push to AWS
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY